name: migrated
description: "migrated project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  flutter_pdfview: ^1.3.4

  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  external_path: ^1.0.3
  http: ^1.2.2
  flutter_downloader: ^1.11.8

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  material_design_icons_flutter: ^7.0.7296
  flutter_octicons: ^1.47.0
  fluttericon: ^2.0.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.1

  image: ^3.3.0
  epubx: ^4.0.0
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdfviewer: ^27.2.5
  google_nav_bar: ^5.0.7

  dio: ^5.7.0
  html: ^0.15.5

  flutter_svg: ^2.0.16

  sqflite: ^2.4.1
  crypto: ^3.0.6
  flutter_riverpod: ^2.6.1
  flutter_inappwebview: ^6.1.5

  get_it: ^8.0.3
  persistent_bottom_nav_bar_v2: ^5.3.1
  pdfrx: ^1.0.94

  flutter_gemini: ^2.0.5

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/leafy_icon.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
