name: migrated
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  flutter_pdfview: ^1.3.4

  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  external_path: ^2.0.1
  http: ^1.2.2
  flutter_downloader: ^1.11.8

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  material_design_icons_flutter: ^7.0.7296
  flutter_cache_manager: ^3.3.1
  flutter_octicons: ^1.47.0
  fluttericon: ^2.0.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.1

  image: ^3.3.0
  epubx: ^4.0.0
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdfviewer: ^27.2.5
  google_nav_bar: ^5.0.7

  dio: ^5.7.0
  html: ^0.15.5

  flutter_svg: ^2.0.16

  sqflite: ^2.4.1
  crypto: ^3.0.6
  flutter_riverpod: ^2.6.1
  flutter_inappwebview: ^6.1.5

  get_it: ^8.0.3
  persistent_bottom_nav_bar_v2: ^5.3.1
  pdfrx: ^1.0.95

  # AI Integration
  google_generative_ai: ^0.2.0

  # Added for metadata storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  percent_indicator: ^4.2.4

  screenshot: ^3.0.0

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

dependency_overrides:
  pdfrx:
    git:
      url: https://github.com/espresso3389/pdfrx.git
      ref: d26c226bfe18d96b9f8ff1dfc9c1e86f0e517724

flutter:
  uses-material-design: true
  assets:
    # chat bg, app icon, etc.
    - assets/images/chat/chat_bg_pattern.png
    - assets/images/leafy_icon.png

    # default ai characters
    - assets/images/ai_characters/professor.png
    - assets/images/ai_characters/student.png
    - assets/images/ai_characters/librarian.png
    - assets/images/ai_characters/artist.png
    - assets/images/ai_characters/scientist.png
    - assets/images/ai_characters/default.png

    # default books
    - assets/pdfs/atomic_habits.pdf
    - assets/pdfs/app_development_flutter.pdf
    - assets/pdfs/business_law.pdf
    - assets/pdfs/gietconchimnhan.pdf
    - assets/document/
    
    # default books's thumbnails
    - assets/images/thumbnails/atomic_habits_thumb.jpg
    - assets/images/thumbnails/business_law_thumb.jpg
    - assets/images/thumbnails/app_development_flutter_thumb.jpg
    - assets/images/thumbnails/gietconchimnhan_thumb.jpg

    - .env
