name: read_leaf
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  supabase_flutter: ^2.3.4
  supabase_auth_ui: ^0.5.4
  injectable: ^2.3.2
  uni_links: ^0.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.0

  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  external_path: ^2.0.1
  http: ^1.2.2
  flutter_downloader: ^1.11.8

  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  material_design_icons_flutter: ^7.0.7296
  flutter_cache_manager: ^3.3.1
  flutter_octicons: ^1.47.0
  fluttericon: ^2.0.0
  url_launcher: ^6.2.4
  share_plus: ^10.1.4

  image: ^3.3.0
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdfviewer: ^28.1.39
  google_nav_bar: ^5.0.7

  dio: ^5.7.0
  html: ^0.15.5

  flutter_svg: ^2.0.16

  sqflite: ^2.4.1
  crypto: ^3.0.6
  flutter_riverpod: ^2.6.1
  flutter_inappwebview: ^6.1.5

  get_it: ^8.0.3

  # AI Integration
  google_generative_ai: ^0.4.6

  # Added for metadata storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  percent_indicator: ^4.2.4

  screenshot: ^3.0.0

  image_picker: ^1.1.2
  bloc: ^9.0.0
  path: ^1.9.0
  pdfrx: ^1.0.101
  epubx: ^4.0.0
  flutter_widget_from_html: ^0.15.3
  scrollable_positioned_list: ^0.3.8
  persistent_bottom_nav_bar_v2: ^5.3.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1
  image_cropper: ^9.0.0

  # Added for sync functionality
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.2
  uuid: ^4.3.3
  logging: ^1.2.0
  cached_network_image: ^3.4.1
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.3.2
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  collection: ^1.19.1

flutter:
  uses-material-design: true
  assets:
    # chat bg, app icon, etc.
    - assets/images/app_logo/logo.jpeg
    - assets/images/chat/chat_bg_pattern.png
    - assets/images/leafy_icon.png
    - assets/icons/
    - assets/images/app_logo/logo_nobg.png

    # default ai characters
    - assets/images/ai_characters/
    - lib/features/characters/data/image_service.dart
    - lib/features/characters/data/personality_traits.json

    # default books
    - assets/pdfs/atomic_habits.pdf
    - assets/pdfs/app_development_flutter.pdf
    - assets/pdfs/business_law.pdf
    - assets/pdfs/gietconchimnhan.pdf
    - assets/document/
    - assets/epubs/
    
    # default books's thumbnails
    - assets/images/thumbnails/

    - .env

    # auth assets
    - assets/images/
    - assets/images/auth/
    - assets/images/auth/google_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo/logo.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_logo/logo.jpeg"
  windows:
    generate: true
    image_path: "assets/images/app_logo/logo.jpeg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo/logo.jpeg"
